{
 "title": "JVM memory dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "memory-demo-j11",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"memory-demo-j11\"}/(2^20))",
     "legendFormat": "Max memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"memory-demo-j11\"}/(2^20))",
     "legendFormat": "Committed memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"memory-demo-j11\"}/(2^20))",
     "legendFormat": "Used memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"memory-demo-j11\"}/(2^20))",
     "legendFormat": "Used heap memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", job=\"memory-demo-j11\"}/(2^20))",
     "legendFormat": "Used nonheap memory [MB]"
    }
   ]
  },
  {
   "title": "memory-demo-j8",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"memory-demo-j8\"}/(2^20))",
     "legendFormat": "Max memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"memory-demo-j8\"}/(2^20))",
     "legendFormat": "Committed memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"memory-demo-j8\"}/(2^20))",
     "legendFormat": "Used memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"memory-demo-j8\"}/(2^20))",
     "legendFormat": "Used heap memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", job=\"memory-demo-j8\"}/(2^20))",
     "legendFormat": "Used nonheap memory [MB]"
    }
   ]
  },
  {
   "title": "memory-demo-j8u181",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"memory-demo-j8u181\"}/(2^20))",
     "legendFormat": "Max memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"memory-demo-j8u181\"}/(2^20))",
     "legendFormat": "Committed memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"memory-demo-j8u181\"}/(2^20))",
     "legendFormat": "Used memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", job=\"memory-demo-j8u181\"}/(2^20))",
     "legendFormat": "Used heap memory [MB]"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", job=\"memory-demo-j8u181\"}/(2^20))",
     "legendFormat": "Used nonheap memory [MB]"
    }
   ]
  }
 ]
}