# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab
    foo:     bar

scrape_configs:

  - job_name: memory-demo-j8
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - memory-demo-j8:8080

  - job_name: memory-demo-j8u181
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - memory-demo-j8u181:8080

  - job_name: memory-demo-j11
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - memory-demo-j11:8080
