on: [workflow_dispatch]

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Build and push j8
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-j8
          push: true
          tags: ghcr.io/ulvestuen/memory-demo-j8:latest
      - name: Build and push j8u181
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-j8u181
          push: true
          tags: ghcr.io/ulvestuen/memory-demo-j8u181:latest
      - name: Build and push j11
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-j11
          push: true
          tags: ghcr.io/ulvestuen/memory-demo-j11:latest
